function recordError(data) {

    console.log("An uncaughtException was found: ", data)
}

export default recordError